### ISSUE TITLE
Manually placed teleport and forced movement activities always say “outside of permitted radius”

### ISSUE THREAD

**Issue by alterNERDtive** [TTimeGaming/fvtt-more-activities#18]
<img width="1340" height="946" alt="Image" src="https://github.com/user-attachments/assets/fe1fbcca-1bc4-4ecd-b3c8-e589c97427eb" />

Dragging anywhere _within_ the permitted radius still says it’s outside of it.

I am playing with grid-aligned templates if that is relevant, and my diagonals setting is 1-2-1.

**Comment by TTimeGaming** [comment]
This has been fixed in this [commit](https://github.com/TTimeGaming/fvtt-more-activities/commit/f18ae561755b9e8aaa39e1955a1b7cdc6498a95b), using the underlying grid to calculate distances rather than manual calculation. This will be included in the next version, I will keep the issue open until then.

**Comment by TTimeGaming** [comment]
Fixed as of [Version 1.5.4](https://github.com/TTimeGaming/fvtt-more-activities/releases/tag/release-1.5.4)

**Comment by alterNERDtive** [comment]
Hmm, I updated to 1.5.4 and I am still getting this error message and cannot drag targets. Tried in a fresh world with no other modules to make sure.

This is _only_ an issue with manual placement and dragging tokens from its popup to the canvas. Unchecking the manual placement box has the teleport work as intended (but then I can’t place anyone manually :)).

**Comment by TTimeGaming** [comment]
Could you provide a breakdown of the setup in your new world? I have tried to replicate your issue but cannot seem to do so.

I am using Alternating 1/2/1 Diagonals with Grid-based Template Shapes enabled, with my Teleport activity configured as so:

<img width="503" height="707" alt="Image" src="https://github.com/user-attachments/assets/4d15bb2c-03d9-490b-9c7e-f09505152a02" />

<img width="778" height="430" alt="Image" src="https://github.com/user-attachments/assets/2a3dc039-6911-4baf-9e55-d5e5ee5dc60b" />

**Comment by alterNERDtive** [comment]
This is the test activity I made in the fresh world:

<img width="446" height="916" alt="Image" src="https://github.com/user-attachments/assets/896ba9e0-0948-41d4-9313-094e871114cd" />

<img width="2178" height="1610" alt="Image" src="https://github.com/user-attachments/assets/5823b75a-dd15-4caf-8586-1d24077eee4d" />

**Comment by alterNERDtive** [comment]
(there are no message in the console except for the notification)

**Comment by TTimeGaming** [comment]
I will reopen this and have to do some looking into this, as I also use FVTT client, so I am stumped without more debugging my end. Apologies this isn't working at present!

**Comment by TTimeGaming** [comment]
Could you put overwrite the teleport.js file in your module with the one attached? I've added some logging to the `_onDragEnd` function (which is determining the out of bounds) to try and narrow this down. If you could export the .zip (because you can't attach .js files in GitHub) and put this in `modules/more-activities/scripts/activities/teleport.js`.

Could you then give me the console output for the four positions highlighted in the image?

<img width="706" height="417" alt="Image" src="https://github.com/user-attachments/assets/e5d85e0f-bfa2-4428-bcb9-be683b69052a" />

[teleport.zip](https://github.com/user-attachments/files/21706863/teleport.zip)

**Comment by alterNERDtive** [comment]
I put that in `scripts/activities`, and now all the extra activities are gone 🤔 

<img width="528" height="900" alt="Image" src="https://github.com/user-attachments/assets/f78a4a3a-bbd6-46fc-bcca-6c28737d013e" />

**Comment by TTimeGaming** [comment]
I'm doing a great job of this. Do you have an error in your console, probably right near the top, complaining about something not being right? Apologies for the back and forth here!

**Comment by alterNERDtive** [comment]
Nope, 

> (no errors in the console) 

(might have edited that in as you were replying)

**Comment by alterNERDtive** [comment]
Restarting Foundry (server side) fixed that one (oO), doing the thing now.

**Comment by alterNERDtive** [comment]
red → blue → pink → green

<img width="1876" height="712" alt="Image" src="https://github.com/user-attachments/assets/30febb0b-fef9-43f3-8d89-808eb468fabb" />

Hope those numbers make more sense to you then to me 💀 

Also same thing in Chromium instead of FVTT Player Client:

<img width="1098" height="762" alt="Image" src="https://github.com/user-attachments/assets/519d26c6-2379-4d54-bb5b-cb50cf05598b" />

As it turns out, the “position clicked” seems to depend on a) browser zoom level and b) foundry canvas zoom level (mouse wheel); here are some random drags onto the same (red) spot with varying of those two:

<img width="1074" height="934" alt="Image" src="https://github.com/user-attachments/assets/42fe1953-f3fb-422a-8480-102308ad2fa0" />

**Comment by alterNERDtive** [comment]
Same order 

<img width="1204" height="1074" alt="Image" src="https://github.com/user-attachments/assets/9623b546-948f-41e9-ad21-a19455da11d2" />

But here is something funny again: I moved the viewport so that the target area was in the very top left of the screen. Then I moved it so that the target are was in the very bottom right of the screen. That also for some reason seems to impact things.

<img width="1196" height="538" alt="Image" src="https://github.com/user-attachments/assets/a1ae7872-846a-4785-9597-a78ab69ef542" />

**Comment by TTimeGaming** [comment]
Thank you for your continued patience trying to ascertain the root. I do have some good news in that I believe that I have traced the cause of the issue, and now just need to rectify it. With that being said, could I ask that you use the attached teleport.js file one more time (restarting the server, as before). This SHOULD be the final time (I hope!) and provide the screenshot of the console (there should, hopefully, be a console line that says something along the lines of "x/y works") 🤞

[teleport.zip](https://github.com/user-attachments/files/21735209/teleport.zip)

**Comment by alterNERDtive** [comment]
Same order as before:

<img width="1320" height="726" alt="Image" src="https://github.com/user-attachments/assets/422f1cad-98d2-41d0-8372-cd2f82e723c8" />

Now it doesn’t matter where I try to drag a token, it always outputs exactly the same thing 🤔

**Comment by alterNERDtive** [comment]
This is just pink:

<img width="1136" height="606" alt="Image" src="https://github.com/user-attachments/assets/aec3931f-4283-4567-8960-0095fa0da170" />

**Comment by TTimeGaming** [comment]
Fundamentally this bug comes down to an issue with the `dragend` event, so I have made some significant changes to the interface to remove the drag/drop functionality and replace it with the clearly working `mouseup` listener on the canvas.

From my testing, this works as intended as at this [commit](https://github.com/TTimeGaming/fvtt-more-activities/commit/8f0515432e3373289fc91100932940ddf4f7c86f). This will be included in the latest release shortly, and should hopefully resolve this longstanding (albeit edge-case) bug.

**Comment by TTimeGaming** [comment]
Fixed as of [Version 1.7.1](https://github.com/TTimeGaming/fvtt-more-activities/releases/tag/release-1.7.1) (I hope).

**Comment by TTimeGaming** [comment]
Final fix for dark mode in this [commit](https://github.com/TTimeGaming/fvtt-more-activities/commit/bed9b4c53648073319550b224ac3f87acdf423fa) to feature in the next release. Cheers 🙂
